services:
  - type: web
    name: ferremas
    env: python
    plan: free
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn taller_ferremas.wsgi:application
    rootDir: ferremas
