services:
  - type: web
    name: ferremas
    env: python
    buildCommand: |
      cd ferremas
      pip install -r requirements.txt
    startCommand: gunicorn taller_ferremas.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: taller_ferremas.settings
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
