name: Ejecucion de pruebas Django

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ferremas  # Aquí ejecutamos comandos dentro de ferremas

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r ../requirements.txt  # Le decimos que el requirements está fuera, en la raíz

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
