name: Ejecucion de pruebas Django

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ferremas

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r ../requirements.txt

      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: taller_ferremas.settings
        run: python manage.py migrate

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: taller_ferremas.settings
        run: python manage.py test